export const demoLibrary = {
  '1': [
    'def evaluate_score(points):',
    '    if points >= 90:',
    '        print("Grade: A")',
    '        print("Excellent work!")',
    '    elif points >= 80:',
    '        print("Grade: B")',
    '        print("Very good effort.")',
    '    else:',
    '        print("Grade: C")',
    '        print("Keep practicing.")',
    '',
    'evaluate_score(85)'
  ].join('\n'),

  '2': [
    'def sort_int_list(lst):',
    '    for i in range(len(lst) - 1):',
    '        if lst[i] > lst[i+1]:',
    '            temp = lst[i]',
    '            lst[i] = lst[i+1]',
    '            lst[i+1] = temp',
    '',
    'sort_int_list([5, 3, 9, 1, 4, 0, 15, 4])'
  ].join('\n'),

  '3': [
    'import time',
    'def run_countdown(seconds):',
    '    while seconds > 0:',
    '        print("Remaining time: " + str(seconds))',
    '        seconds = seconds - 1',
    '        time.sleep(1)',
    '    print("System activated.")',
    '',
    'run_countdown(10)'
  ].join('\n'),

  '4': [
    'def calculate_area(radius):',
    '    if radius <= 0:',
    '        return 0',
    '    ',
    '    pi_value = 3.14159',
    '    area = pi_value * (radius ** 2)',
    '    ',
    '    if area > 100 or radius == 10:',
    '        print("Large circle")',
    '    elif area > 0 and area <= 100:',
    '        print("Small circle")',
    '    else:',
    '        print("Invalid")',
    '        ',
    '    for i in range(5):',
    '        while i < 3:',
    '            i += 1',
    '            ',
    '    return area',
    '',
    'calculate_area(5)'
  ].join('\n'),

  '5': [
    'def analyze_fibonacci(limit):',
    '    a, b = 0, 1',
    '    count = 0',
    '    print("Generating sequence up to: " + str(limit))',
    '    while a < limit:',
    '        print("Current Term: " + str(a))',
    '        if a % 2 == 0:',
    '            print("Note: This number is Even.")',
    '        else:',
    '            print("Note: This number is Odd.")',
    '        ',
    '        a, b = b, a + b',
    '        count += 1',
    '    print("Generated " + str(count) + " terms.")',
    '',
    'analyze_fibonacci(100)'
  ].join('\n'),

  '6': [
    'def filter_text_list(items):',
    '    print("Input count: " + str(len(items)))',
    '    results = []',
    '    for word in items:',
    '        if len(word) > 5:',
    '            print("Keeping long word: " + word)',
    '            results.append(word)',
    '        elif len(word) == 0:',
    '            print("Discarding empty string.")',
    '        else:',
    '            print("Word too short: " + word)',
    '',
    '    print("Filter complete. Items kept: " + str(len(results)))',
    '    return results',
    '',
    'filter_text_list(["apple", "elephant", "", "cat", "computer"])'
  ].join('\n'),

  '7': [
    'def search_for_value(target, max_range, lst):',
    '    current = 0',
    '    found = False',
    '    print("Starting search for: " + str(target))',
    '',
    '    while current < max_range:',
    '        print("Checking value: " + str(current))',
    '        if lst[current] == target:',
    '            print("Target found!")',
    '            found = True',
    '            break',
    '        current += 1',
    '',
    '    if found:',
    '        print("Search successful.")',
    '    else:',
    '        print("Target not in range.")',
    '',
    'search_for_value(7, 20, list(range(20)))'
  ].join('\n'),

  '8': [
    'class BankAccount:',
    '    def __init__(self, owner, balance=0):',
    '        self.owner = owner',
    '        self.balance = balance',
    '',
    '    def deposit(self, amount):',
    '        self.balance += amount',
    '',
    '    def withdraw(self, amount):',
    '        if amount > self.balance:',
    '            print("Insufficient funds")',
    '        else:',
    '            self.balance -= amount',
    '',
    '    def __str__(self):',
    '        return f"{self.owner}: £{self.balance}"',
    '',
    'account = BankAccount("Alice", 100)',
    'account.deposit(50)',
    'print(account)'
  ].join('\n'),

  '9': [
    'def factorial(n):',
    '    if n < 0:',
    '        raise ValueError("Non-negative only")',
    '    if n in (0, 1):',
    '        return 1',
    '    return n * factorial(n - 1)',
    '',
    'def fibonacci(n):',
    '    if n <= 1:',
    '        return n',
    '    return fibonacci(n - 1) + fibonacci(n - 2)',
    '',
    'print("Factorial 5:", factorial(5))',
    'print("Fibonacci 6:", fibonacci(6))'
  ].join('\n'),

  '10': [
    'def create_grid(rows, cols):',
    '    grid = []',
    '    for r in range(rows):',
    '        row = []',
    '        for c in range(cols):',
    '            row.append((r, c))',
    '        grid.append(row)',
    '    return grid',
    '',
    'def print_grid(grid):',
    '    for row in grid: print(row)',
    '',
    'g = create_grid(3, 4)',
    'print_grid(g)'
  ].join('\n')
};